on:
  push:  # Triggers the action on every commit push
    branches:
      - main  # Specify branches as needed (e.g., "main", "dev")

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
    - name: Send Telegram Message
      run: |
        message="${{ github.actor }} created a commit:\nCommit message: ${{ github.event.head_commit.message }}\n\nRepository: ${{ github.repository }}\n\nSee changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
        
        curl -s -X POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&message_thread_id=${{ secrets.TELEGRAM_MESSAGE_THREAD_ID }}&text=$message"
